### PR TITLE
Use native `.tar.lzma` support in `Omnibus::NetFetcher`

### PR DESCRIPTION
**Pull request by schisamo**
See chef/omnibus#572 for full details.

Test CI run: http://manhattan.ci.chef.co/job/harmony-trigger-ad_hoc/24/downstreambuildview/

/cc @chef/engineering-services

### CODE REVIEW

**Comment by sethvargo** [comment]
:+1:

**Comment by schisamo** [comment]
So it looks like libyaml-windows (and other [knap-build](https://github.com/oneclick/knap-build) produced archives) don't follow the `name-version/` toplevel directory convention of regular tarballs. `Omnibus::NetFetcher` assumes this convention in its extraction logic:
https://github.com/chef/omnibus/blob/c1775a6ce1f9ed7b3d74fe2442cace785971bac5/lib/omnibus/fetchers/net_fetcher.rb#L261-L281

**Comment by yzl** [comment]
:+1:

**Comment by jaym** [comment]
@chefsalim schisamo had the same problems we were having. He used `relative_path 'bin'`

**Pull request merged**
