### PR TITLE
Add Licensing

### PR DESCRIPTION
**Pull request by schisamo**
This is to prepare for the changes that will come in: https://github.com/chef-cookbooks/opscode-ci/pull/467

/cc @chef/engineering-services

### CODE REVIEW

**Comment by scotthain** [comment]
👍 I'm assuming we're removing rsync because GPLv3?

**Comment by schisamo** [comment]
@scotthain I'm removing it cause I had issues compiling it and `popt` on Windows. The few things we compile don't matter all that much.

**Comment by scotthain** [comment]
@schisamo totally - was just curious, I'm fine with removing it.

**Comment by sersut** [comment]
Nice! 👍

**Comment by yzl** [comment]
👍

**Pull request merged**
